package com.bitflippin.bedivere.form;

import com.bitflippin.bedivere.model.Claim;
import com.bitflippin.bedivere.model.Source;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class MainForm {
    public JPanel contentPanel;
    public JButton saveButton;
    public JButton addClaimButton;
    public JButton addSourceButton;
    public JTabbedPane detailsTabbedPane;
    public JList<Claim> claimsList;
    public JList<Source> sourcesList;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        contentPanel.add(panel1, BorderLayout.NORTH);
        saveButton = new JButton();
        saveButton.setText("Save");
        panel1.add(saveButton);
        addClaimButton = new JButton();
        addClaimButton.setText("Add Claim");
        panel1.add(addClaimButton);
        addSourceButton = new JButton();
        addSourceButton.setText("Add Source");
        panel1.add(addSourceButton);
        final JSplitPane splitPane1 = new JSplitPane();
        contentPanel.add(splitPane1, BorderLayout.CENTER);
        final JScrollPane scrollPane1 = new JScrollPane();
        splitPane1.setLeftComponent(scrollPane1);
        final JTabbedPane tabbedPane1 = new JTabbedPane();
        scrollPane1.setViewportView(tabbedPane1);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Claims", panel2);
        claimsList = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        claimsList.setModel(defaultListModel1);
        panel2.add(claimsList, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Sources", panel3);
        sourcesList = new JList();
        panel3.add(sourcesList, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JScrollPane scrollPane2 = new JScrollPane();
        splitPane1.setRightComponent(scrollPane2);
        detailsTabbedPane = new JTabbedPane();
        scrollPane2.setViewportView(detailsTabbedPane);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }

}
